import { NODE_ENV } from '../../configs/env.config';

const PRODUCTION_ENV = NODE_ENV;
const VERBOSE_LOGGING_LVL = 'verbose';
const INFO_LOGGING_LVL = 'info';
const DEFAULT_PAGINATION_LIMIT = 25;
const MAX_PAGINATION_LIMIT = 100;
const DEFAULT_PAGINATION_PAGE = 1;

module.exports = {
  PRODUCTION_ENV,
  VERBOSE_LOGGING_LVL,
  INFO_LOGGING_LVL,
  DEFAULT_PAGINATION_LIMIT,
  MAX_PAGINATION_LIMIT,
  DEFAULT_PAGINATION_PAGE,
};
